mock_movies = [
    {
        "id": "1",
        "title": "Spider Man",
        "image": "https://play-lh.googleusercontent.com/PQW6qebXTYwtpgYCPsGu2qt7YivGjDrEPH_yfkgNpPJUXcyoJfu-ZAE3oRGdKzc3TAqV",
        "rating": 4.8,
        "description": "Peter Parker é um jovem comum até ser picado por uma aranha radioativa e ganhar superpoderes. Agora ele deve aprender a usar suas habilidades para proteger Nova York como o Homem-Aranha.",
        "year": 2002,
        "genre": "Ação, Aventura",
        "duration": "121 min",
        "director": "Sam Raimi",
    },
    {
        "id": "2",
        "title": "Batman",
        "image": "https://m.media-amazon.com/images/M/MV5BZmI5MjkxOWUtNGNkOS00NDRmLWJlOWUtODhmNGIxODY2ZjIwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        "rating": 3.7,
        "description": "Bruce Wayne luta contra o crime em Gotham City como o vigilante mascarado Batman, enfrentando vilões perigosos e protegendo os inocentes.",
        "year": 2005,
        "genre": "Ação, Drama",
        "duration": "140 min",
        "director": "Christopher Nolan",
    },
    {
        "id": "3",
        "title": "Justice League",
        "image": "https://br.web.img2.acsta.net/pictures/17/10/23/19/55/0260439.jpg",
        "rating": 2.3,
        "description": "Batman e Wonder Woman recrutam uma equipe de meta-humanos para proteger o mundo de uma ameaça catastrófica.",
        "year": 2017,
        "genre": "Ação, Aventura, Fantasia",
        "duration": "120 min",
        "director": "Zack Snyder",
    },
    {
        "id": "4",
        "title": "A Forja",
        "image": "https://br.web.img2.acsta.net/img/67/e4/67e451cd6d1ceb7a0d2d5cdd4ef50317.jpg",
        "rating": 1.2,
        "description": "Um drama inspirador sobre fé, família e a importância de nunca desistir dos seus sonhos.",
        "year": 2024,
        "genre": "Drama",
        "duration": "123 min",
        "director": "Alex Kendrick",
    },
    {
        "id": "5",
        "title": "Avengers: Endgame",
        "image": "https://upload.wikimedia.org/wikipedia/pt/thumb/9/9b/Avengers_Endgame.jpg/250px-Avengers_Endgame.jpg",
        "rating": 4.9,
        "description": "Os Vingadores restantes devem encontrar uma maneira de reverter as ações de Thanos e restaurar o equilíbrio do universo.",
        "year": 2019,
        "genre": "Ação, Aventura, Drama",
        "duration": "181 min",
        "director": "Anthony Russo, Joe Russo",
    },
    {
        "id": "6",
        "title": "The Dark Knight",
        "image": "https://play-lh.googleusercontent.com/auIs5tjWlLYaFPGClZOJ7m5YVbnX6uBvz0X02r8TkwFKdzE53ww2MqWSS9gU0YNqoYwvpg",
        "rating": 4.7,
        "description": "Batman enfrenta o Coringa, um criminoso psicopata que quer mergulhar Gotham City no caos.",
        "year": 2008,
        "genre": "Ação, Crime, Drama",
        "duration": "152 min",
        "director": "Christopher Nolan",
    },
    {
        "id": "7",
        "title": "Inception",
        "image": "https://upload.wikimedia.org/wikipedia/pt/8/84/AOrigemPoster.jpg",
        "rating": 4.8,
        "description": "Um ladrão que invade os sonhos das pessoas recebe a missão de implantar uma ideia na mente de um alvo.",
        "year": 2010,
        "genre": "Ação, Ficção Científica, Suspense",
        "duration": "148 min",
        "director": "Christopher Nolan",
    },
    {
        "id": "8",
        "title": "Interstellar",
        "image": "https://upload.wikimedia.org/wikipedia/pt/3/3a/Interstellar_Filme.png",
        "rating": 4.6,
        "description": "Um grupo de exploradores viaja por um buraco de minhoca no espaço em busca de um novo lar para a humanidade.",
        "year": 2014,
        "genre": "Aventura, Drama, Ficção Científica",
        "duration": "169 min",
        "director": "Christopher Nolan",
    },
]
