"""createtable2

Revision ID: d37c44512960
Revises: 509fa126237a
Create Date: 2025-07-10 21:23:38.323136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37c44512960'
down_revision: Union[str, Sequence[str], None] = '509fa126237a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comments', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'comments', 'movies', ['movieId'], ['id'])
    op.create_foreign_key(None, 'favorites', 'movies', ['movieId'], ['id'])
    op.create_foreign_key(None, 'favorites', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'histories', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'histories', 'movies', ['movieId'], ['id'])
    op.add_column('movies', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('movies', sa.Column('genre', sa.String(length=100), nullable=False))
    op.add_column('movies', sa.Column('duration', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'duration')
    op.drop_column('movies', 'genre')
    op.drop_column('movies', 'description')
    op.drop_constraint(None, 'histories', type_='foreignkey')
    op.drop_constraint(None, 'histories', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    # ### end Alembic commands ###
